[package]
name = "cpro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clib = { git = "https://github.com/leefordjudes/clib", "version" = "0.1.1" }